# Generated by Django 4.2 on 2025-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
