# Generated by Django 4.2 on 2025-11-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_userinfo_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='verification_code_expiry',
            new_name='email_token_expiry',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='verification_code',
        ),
    ]
