# Generated by Django 4.2 on 2025-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_userinfo_gender_userinfo_location_userinfo_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='yearsOfExperience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
