# Generated by Django 4.2 on 2025-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_userinfo_yearsofexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
