# Generated by Django 4.2 on 2025-12-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_patient_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
