# Generated by Django 4.2 on 2025-12-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_userinfo_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
