# Generated by Django 4.2 on 2025-12-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoom_appointment',
            name='original_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointment.zoom_appointment'),
        ),
        migrations.AddField(
            model_name='zoom_appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoom_appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoom_appointment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
