# Generated by Django 4.2 on 2026-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_alter_patient_age_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_appointment',
            name='admin_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
