# Generated by Django 4.2 on 2026-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_zoom_appointment_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom_appointment',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='zoom_appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reschedule_requested', 'Reschedule Requested')], default='pending', max_length=20),
        ),
    ]
