# Generated by Django 4.2 on 2026-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0026_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom_appointment',
            name='meeting_details',
            field=models.TextField(blank=True, help_text='Meeting instructions/details posted by doctor', null=True),
        ),
        migrations.AddField(
            model_name='zoom_appointment',
            name='meeting_details_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
