# Generated by Django 4.2 on 2026-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_zoom_appointment_meeting_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True, help_text="Doctor's biography/biography", null=True),
        ),
    ]
