# Generated by Django 4.2 on 2026-04-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0028_userinfo_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='certifications',
            field=models.TextField(blank=True, help_text="Doctor's certifications (one per line)", null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='education',
            field=models.TextField(blank=True, help_text="Doctor's education background (one per line)", null=True),
        ),
    ]
